version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "fpllex"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
    build:
        commands:
            - echo Build started on `date`
    post_build:
         commands:
            - echo Build completed on `date`
            - aws s3 cp . s3://${S3_BUCKET}/ --recursive --exclude ".git/*" --exclude "README.md" --exclude ".DS_Store" --exclude "buildspec.yml"